name: clang-format

on:
  workflow_call:
    inputs:
      sparse_paths:
        description: "Newline-separated sparse checkout paths"
        required: false
        type: string
        default: |
          .github

permissions:
  contents: write

jobs:
  format-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: ${{ inputs.sparse_paths }}

      - name: Run clang-format
        run: |
          find . -type f \( -iname "*.cpp" -o -iname "*.h" -o -iname "*.c" \) \
            | xargs clang-format -i

      - name: Commit and push changes if any
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: format code with clang-format"

      - name: Print result
        if: steps.auto-commit.outputs.changes_detected == 'false'
        run: echo "No changes to commit"
